apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avesair
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  project: default
  source:
    repoURL: "https://github.com/Gokul-Mylsami/avesair-helm-charts.git"
    path: "."
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
