apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gokulmsfag/finaltask-backend:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: NODE_ENV
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: MONGO_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              value: 1d
            - name: EMAIL_SERVICE
              value: gmail
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: EMAIL_USERNAME
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: EMAIL_PASSWORD
            - name: FRONTEND_URL
              value: frontend.gokulmylsami.me
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
