apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteMany"
  storageClassName: aws-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b160979a18957eec

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-2
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteMany"
  storageClassName: aws-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0fc3deefe7670967a
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-3
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteMany"
  storageClassName: aws-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06f24b7d93b73a626
