apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eks-secret-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-irsa

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: eks-secret-store
    kind: SecretStore
  target:
    name: application-secrets
  data:
    - secretKey: MONGO_URL
      remoteRef:
        key: eksSecretKeys
        property: MONGO_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: eksSecretKeys
        property: JWT_SECRET
    - secretKey: EMAIL_USERNAME
      remoteRef:
        key: eksSecretKeys
        property: EMAIL_USERNAME
    - secretKey: EMAIL_PASSWORD
      remoteRef:
        key: eksSecretKeys
        property: EMAIL_PASSWORD
    - secretKey: SLACK_URL
      remoteRef:
        key: eksSecretKeys
        property: SLACK_URL
