{
 "title": "App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Users active",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myapp_total_no_of_users_daily_login{app=\"aves-air\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total No of Flights",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myapp_total_no_of_flights{app=\"aves-air\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticket Bookings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "myapp_total_bookings_today{app=\"aves-air\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Booking Catergories",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(myapp_total_no_of_economy_seats_booked{app=\"aves-air\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(myapp_total_no_of_first_class_seats_booked{app=\"aves-air\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(myapp_total_no_of_premium_class_seats_booked{app=\"aves-air\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No of Tickets Cancelled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "myapp_total_no_tickets_cancelled{app=\"aves-air\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No of http request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(myapp_http_request_count{app=\"aves-air\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "myapp_http_request_duration_bucket{app=\"aves-air\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "myapp_http_request_duration_bucket{app=\"aves-air\",method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}