{
 "title": "Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage of Instance 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"3.86.243.39:30910\", cpu=~\"0|1\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage of Instance 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"44.211.87.190:30910\", cpu=~\"0|1\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage of Instance 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes{instance=\"3.86.243.39:30910\"} + node_memory_Buffers_bytes{instance=\"3.86.243.39:30910\"} + node_memory_Cached_bytes{instance=\"3.86.243.39:30910\"}) / node_memory_MemTotal_bytes{instance=\"3.86.243.39:30910\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage of Instance 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes{instance=\"44.211.87.190:30910\"} + node_memory_Buffers_bytes{instance=\"44.211.87.190:30910\"} + node_memory_Cached_bytes{instance=\"44.211.87.190:30910\"}) / node_memory_MemTotal_bytes{instance=\"44.211.87.190:30910\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}