apiVersion: v1
kind: Secret
metadata:
  name: docker-repo
type: Opaque
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMzI1OTY4MzA5MTUuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHt9LAoJCSIzNjg2MjU0MTUxMDAuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAid2luY3JlZC5leGUiCn0=
