apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteMany"
  storageClassName: aws-efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b870f87a44595164

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-2
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteMany"
  storageClassName: aws-efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-073b250e348f9b134
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-3
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteMany"
  storageClassName: aws-efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0302c4c0f6c5e69ce
---

