name: Build Backend Docker image
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "The tag of the image to build"
        default: "latest"

jobs:
  Backend-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build backend docker image
        run: docker build -t ${{ secrets.DOCKER_REPO }}/backend:${{ github.event.inputs.image-tag }} ./Backend

      - name: Push backend docker image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.DOCKER_REPO }}
          docker push ${{ secrets.DOCKER_REPO }}/backend:${{ github.event.inputs.image-tag }}

  Update-New-Image-Tag:
    runs-on: ubuntu-latest
    needs: Backend-Docker-Image
    steps:
      - name: Get code
        run: |
          git clone https://${{ secrets.ACCESS_GITHUB }}@github.com/Gokul-Mylsami/avesair-helm-charts.git
          cd avesair-helm-charts
      - name: Update the image tag
        run: |
          new_tag=${{ github.event.inputs.image-tag }}
          cd avesair-helm-charts
          sed -i "s/\(backendTag:\s*\).*/\1'$new_tag'/" values.yaml
      - name: Show the values
        run: |
          cd avesair-helm-charts
          cat values.yaml
      - name: Commit the changes
        run: |
          cd avesair-helm-charts
          git add .
          git config --global user.email "gokulmylsami@gmail.com"
          git config --global user.name "Gokul-Mylsami"
          git commit -m "Update the Backend image tag to ${{ github.event.inputs.image-tag }}"
          git push
