name: Build Frontend Docker image
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "The tag of the image to build"
        required: true
jobs:
  frontendBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build frontend docker image
        run: docker build -t ${{ secrets.DOCKER_REPO }}/frontend:${{ github.event.inputs.image-tag }} ./Frontend

      - name: Push frontend docker image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.DOCKER_REPO }}
          docker push ${{ secrets.DOCKER_REPO }}/frontend:${{ github.event.inputs.image-tag }}

  updateNewImage:
    needs: frontendBuild
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        run: |
          git clone https://github.com/Gokul-Mylsami/avesair-helm-charts.git
          cd avesair-helm-charts
