name: Build Frontend Docker image
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "The tag of the image to build"
        required: true
  push:
    branches:
      - main
    paths:
      - Frontend/**

jobs:
  Frontend-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Image Tag
        id: set-image-tag
        run: echo "::set-output name=tag::${{ github.event.inputs.image-tag || 'latest' }}"

      - name: Build frontend docker image
        run: docker build -t ${{ secrets.DOCKER_REPO }}/frontend:${{ steps.set-image-tag.outputs.tag }} ./Frontend

      - name: Push frontend docker image
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.DOCKER_REPO }}
          docker push ${{ secrets.DOCKER_REPO }}/frontend:${{ steps.set-image-tag.outputs.tag }}

  updateNewImage:
    runs-on: ubuntu-latest
    needs: Frontend-Build
    steps:
      - name: Get code
        run: |
          git clone https://${{ secrets.ACCESS_GITHUB }}@github.com/Gokul-Mylsami/avesair-helm-charts.git
          cd avesair-helm-charts

      - name: Set Image Tag
        id: set-image-tag
        run: echo "::set-output name=tag::${{ github.event.inputs.image-tag || 'latest' }}"

      - name: Update the image tag
        run: |
          new_tag=${{ steps.set-image-tag.outputs.tag }}
          cd avesair-helm-charts
          sed -i "s/\(frontendTag:\s*\).*/\1$new_tag/" values.yaml
      - name: Show the values
        run: |
          cd avesair-helm-charts
          cat values.yaml
      - name: Commit the changes
        run: |
          cd avesair-helm-charts
          git add .
          git config --global user.email "gokulmylsami@gmail.com"
          git config --global user.name "Gokul-Mylsami"
          git commit -m "Update the frontend image tag to ${{ steps.set-image-tag.outputs.tag }}"
          git push
