name: Testing
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "The tag of the image to build"
        required: true
jobs:
  updateNewImage:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: |
          git clone https://${{ secrets.ACCESS_GITHUB }}@github.com/Gokul-Mylsami/avesair-helm-charts.git
          cd avesair-helm-charts
      - name: Update the image tag
        run: |
          new_tag=${{ github.event.inputs.image-tag }}
          cd avesair-helm-charts
          sed -i "s/\(frontendTag:\s*\).*/\1$new_tag/" values.yaml
      - name: Show the values
        run: |
          cd avesair-helm-charts
          cat values.yaml
      - name: Commit the changes
        run: |
          cd avesair-helm-charts
          git add .
          git config --global user.email "gokulmylsami@gmail.com"
          git config --global user.name "Gokul-Mylsami"
          git commit -m "Update the frontend image tag to ${{ github.event.inputs.image-tag }}"
          git push
